name: helloWorld
on: [push, workflow_dispatch]
jobs: 
  run-helloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: runCompile
        run: javac helloWorld.java && java helloWorld
      
